/**
 * store type 常量
 * 
 */

export enum RECOMMEND_ACTION_TYPE {
  // 轮播图数据
  CHANGE_TOP_BANNERS = 'RECOMMEND/CHANGE_TOP_BANNERS',
  // 热门推荐数据
  CHANGE_HOT_RECOMMED = 'RECOMMEND/CHANGE_HOT_RECOMMED',
  // 新碟上架数据
  CHANGE_NEW_ALBUM = 'RECOMMEND/CHANGE_NEW_ALBUM',
  // 榜单飙升榜数据
  CHANGE_UP_RANKING = 'RECOMMEND/CHANGE_UP_RANKING',
  // 榜单新歌榜数据
  CHANGE_NEW_RANKING = 'RECOMMEND/CHANGE_NEW_RANKING',
  // 榜单原创榜数据
  CHANGE_ORIGIN_RANKING = 'RECOMMEND/CHANGE_ORIGIN_RANKING'
}