export enum PLAYER_ACTION_TYPE {
  CHANGE_CURRENT_SONG = "PLAYER/CHANGE_CURRENT_SONG",
  CHANGE_PLAY_LIST = "PLAYER/CHANGE_PLAY_LIST",
  CHANGE_CURRENT_SONG_INDEX = "PLAYER/CHANGE_CURRENT_SONG_INDEX",
  CHANGE_SEQUENCE = "PLAYER/CHANGE_SEQUENCE",
  CHANGE_LYRIC = "PLAYER/CHANGE_LYRIC",
  CHANGE_CURRENT_LYRIC_INDEX = "PLAYER/CHANGE_CURRENT_LYRIC_INDEX"
}

export enum SEQUENCE_TYPE {
  SEQUENCE_CIRCLE = 0, // 单曲循环
  SEQUENCE_RANDOM = 1, // 随机播放
  SEQUENCE_SINGLE = 2 // 单曲循环
}